version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID} --region=us-east-1
          when: on_fail

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create stack
          command: |
            aws cloudformation create-stack  \
              --template-body template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region=us-east-1
      - destroy_environment

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
